### PR TITLE
Pass private keys to privileged engine methods

### PR DESCRIPTION
**Pull request by samholmes**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204056629741205
  - https://app.asana.com/0/0/1204207855596351

### CODE REVIEW

**Review by swansontec — APPROVED** [review]
This was much simpler than I expected it to be! Let's hold off on merging until we have clarity on Monero and ZCash, though. More changes may be needed for those guys.

**Review by swansontec — CHANGES_REQUESTED** [review]
Some small changes. Plus maybe the `opts: { privateKeys: {} }` thing we talked about. I would prefer "private" over "unsafe", since that's the term everybody uses in the crypto space.

**Review by swansontec — CHANGES_REQUESTED** [review]
This is really close to being perfect! I am super happy with the way it's coming together. Just a few things left to look at.

**Comment by samholmes** [comment]
Make `privateKeys: object` a parameter for `signTx`. Also make `privateKeys: object` type for options argument.

**Review by swansontec — APPROVED** [review]
This will work. I see that you skipped the one optional error-message change, but otherwise this is what we want.

**Pull request merged**
