### PR TITLE
Faa.st exchange plugin implementation

### PR DESCRIPTION
**Pull request by dylanseago**
Implement an exchange plugin for the [Faa.st](https://faa.st) service.

Manually tested by applying commits to edge-core-js@0.12.20, installing on edge-react-gui@1.4.5 and running on a Google Pixel 3 XL running Android 9.0.

### CODE REVIEW

**Comment by swansontec** [comment]
Thanks for fixing those. We would like to enable support for the [affiliate feature](https://api.faa.st/#affiliate-program) before we ship this in our app, so there's a little more coordination that needs to happen still.

**Comment by dylanseago** [comment]
@swansontec Would your preferred way to enable the affiliate feature be to add an initOptions like changelly so you can specify an apiKey in `env.json` in `edge-react-gui`?

**Comment by swansontec** [comment]
Update: We are targeting Faa.st for our January release, so we'll merge this branch once the window for that opens up.

**Comment by dylanseago** [comment]
@swansontec Affiliate options have been added. Use [this endpoint](https://api.faa.st/#affiliate-register-post) to register then provide your `affiliateId` (but not secret) in the [`FAAST_INIT`](https://github.com/EdgeApp/edge-react-gui/blob/9a3447a5ba4c27daef4828ec2eaf7bea93b3508d/env.example.json#L16) env. An affiliate GUI will be available before January.

**Comment by swansontec** [comment]
We try to avoid merge commits in our branches, so I rebased everything onto develop & opened a new pull request with that code. Merged & approved.

**Comment by paullinator** [comment]
@dylanseago Is there an API to query all transactions done with an API key? All other swap exchange partners have this.

**Comment by dylanseago** [comment]
@paullinator There is an endpoint for that. It's currently undocumented but you can use: `https://api.faa.st/api/v2/public/swaps?affiliate_id=XXXX`

You can also use our [affiliate dashboard](https://faa.st/affiliates) to see them amongst other stats. Note that it's still under development so earnings history and requesting a withdrawal isn't operational yet.

**Pull request closed without merging**
